"""
Plan Generator Skill for AI Employee

This skill creates Plan.md files based on tasks and objectives.
It implements the Claude reasoning loop that generates structured plans.
"""

import os
from pathlib import Path
from datetime import datetime
import json
import re


class PlanGeneratorSkill:
    """Skill to generate structured plans based on tasks and objectives."""

    def __init__(self, vault_path):
        self.vault_path = Path(vault_path)
        self.plans_dir = self.vault_path / 'Plans'
        self.needs_action_dir = self.vault_path / 'Needs_Action'
        self.company_handbook_path = self.vault_path / 'Company_Handbook.md'

        # Ensure directories exist
        self.plans_dir.mkdir(exist_ok=True)
        self.needs_action_dir.mkdir(exist_ok=True)

        # Load company handbook for reference
        self.handbook_rules = self._load_company_handbook()

    def _load_company_handbook(self):
        """Load company handbook rules for reference."""
        if self.company_handbook_path.exists():
            try:
                content = self.company_handbook_path.read_text(encoding='utf-8')
                return content
            except Exception as e:
                print(f"Error loading company handbook: {e}")
                return ""
        return ""

    def generate_plan_from_task(self, task_description, task_priority="medium", task_deadline=None):
        """Generate a structured plan from a task description."""
        plan_id = f"PLAN_{int(datetime.now().timestamp())}_{task_priority}"

        # Create a structured plan with YAML frontmatter
        plan_content = f"""---
type: plan
plan_id: {plan_id}
task_description: "{task_description}"
priority: {task_priority}
status: draft
created_at: {datetime.now().isoformat()}
author: ai_employee
estimated_duration: TBA
dependencies: []
tags: []
---

# Plan: {task_description}

## Objective
{task_description}

## Context
Based on the task requirements and company guidelines.

## Constraints
- Follow company handbook policies
- Adhere to communication guidelines
- Maintain quality standards
- Meet deadline requirements

## Resources Needed
- Access to company systems
- Relevant documentation
- Time allocation

## Success Criteria
- Task completed as specified
- Quality standards met
- Timeline adhered to
- Stakeholder satisfaction

## Assumptions
- Required resources are available
- No unexpected obstacles
- Clear requirements remain unchanged

## Risks
- Resource constraints
- Timeline pressure
- Changing requirements

## Mitigation Strategies
- Early identification of resource needs
- Regular progress checks
- Clear communication with stakeholders

## Action Steps
1. [ ] Analyze the task requirements
2. [ ] Gather necessary information
3. [ ] Develop solution approach
4. [ ] Execute the plan
5. [ ] Review and refine as needed
6. [ ] Complete the task
7. [ ] Document outcomes

## Timeline
- Start Date: {datetime.now().strftime('%Y-%m-%d')}
- End Date: {task_deadline or 'TBD'}
- Milestones: TBD

## Dependencies
- [ ] Prerequisite tasks (if any)
- [ ] External resources (if any)
- [ ] Approvals (if any)

## Stakeholders
- Task assigner
- End users (if applicable)
- Reviewers (if applicable)

## Communication Plan
- Progress updates: As needed
- Issues escalation: Per company handbook
- Completion notification: Upon task completion

## Review Points
- Plan validation: Before execution
- Mid-point review: During execution
- Final review: Upon completion

## Approval Required
This plan may require approval before execution depending on task sensitivity.

---
Plan generated by Plan Generator Skill on {datetime.now().isoformat()}
"""

        plan_filename = f"{plan_id}.md"
        plan_path = self.plans_dir / plan_filename
        plan_path.write_text(plan_content, encoding='utf-8')

        print(f"Generated plan: {plan_path.name}")
        return str(plan_path)

    def generate_detailed_plan(self, objective, requirements=None, constraints=None, timeline=None):
        """Generate a more detailed plan with specific requirements."""
        plan_id = f"DETAILED_PLAN_{int(datetime.now().timestamp())}"

        # Create a more detailed plan structure
        plan_content = f"""---
type: detailed_plan
plan_id: {plan_id}
objective: "{objective}"
status: draft
created_at: {datetime.now().isoformat()}
author: ai_employee
review_required: true
---

# Detailed Plan: {objective}

## Executive Summary
This plan outlines the approach to achieve the stated objective.

## Objective
{objective}

## Requirements
{requirements or 'Requirements will be defined during planning.'}

## Constraints
{constraints or 'Constraints will be identified during planning.'}

## Timeline
{timeline or 'Timeline will be developed during planning.'}

## Phase 1: Planning and Preparation
- [ ] Define specific requirements
- [ ] Identify necessary resources
- [ ] Establish success metrics
- [ ] Plan risk mitigation strategies

## Phase 2: Execution
- [ ] Execute planned activities
- [ ] Monitor progress
- [ ] Address issues as they arise
- [ ] Adjust plan as needed

## Phase 3: Review and Completion
- [ ] Verify objectives met
- [ ] Document outcomes
- [ ] Obtain necessary approvals
- [ ] Close out the task

## Resources Required
- Personnel: TBD
- Equipment: TBD
- Budget: TBD
- Time: TBD

## Risk Assessment
- Low Risk: Tasks within normal scope
- Medium Risk: Some complexity involved
- High Risk: Significant unknowns or dependencies

## Success Metrics
- [ ] Objective achieved
- [ ] Quality standards met
- [ ] Timeline adherence
- [ ] Stakeholder satisfaction

## Next Steps
1. Review this plan with stakeholders
2. Refine details as needed
3. Begin execution phase
4. Monitor and adjust as necessary

## Company Handbook Compliance
This plan adheres to the guidelines in the Company Handbook:
{self.handbook_rules[:500]}...

---
Detailed plan generated by Plan Generator Skill on {datetime.now().isoformat()}
"""

        plan_filename = f"{plan_id}.md"
        plan_path = self.plans_dir / plan_filename
        plan_path.write_text(plan_content, encoding='utf-8')

        print(f"Generated detailed plan: {plan_path.name}")
        return str(plan_path)

    def process_needs_action_for_planning(self):
        """Process items in Needs_Action that require planning."""
        needs_action_files = list(self.needs_action_dir.glob("*.md"))
        created_plans = []

        for file_path in needs_action_files:
            content = file_path.read_text(encoding='utf-8')

            # Look for tasks that require planning
            if any(keyword in content.lower() for keyword in ['plan', 'schedule', 'organize', 'coordinate', 'implement']):
                # Extract task description
                lines = content.split('\n')
                task_desc = "Task from Needs_Action file"

                for line in lines:
                    if line.startswith('# '):  # Main title
                        task_desc = line[2:].strip()
                        break
                    elif line.startswith('## Objective'):  # Objective section
                        # Get next line which should contain the objective
                        try:
                            idx = lines.index(line)
                            if idx + 1 < len(lines):
                                task_desc = lines[idx + 1].strip()
                                break
                        except ValueError:
                            pass

                # Generate a plan for this task
                plan_path = self.generate_plan_from_task(task_desc)
                created_plans.append({
                    'task_file': str(file_path),
                    'plan_file': plan_path,
                    'task_description': task_desc
                })

        return created_plans

    def update_plan_status(self, plan_file_path, new_status):
        """Update the status of a plan."""
        plan_path = Path(plan_file_path)

        # Read the current content
        content = plan_path.read_text(encoding='utf-8')

        # Update the status in the YAML frontmatter
        lines = content.split('\n')
        updated_lines = []
        in_frontmatter = False
        frontmatter_end_idx = -1

        for i, line in enumerate(lines):
            if line.strip() == '---':
                if not in_frontmatter:
                    in_frontmatter = True
                    updated_lines.append(line)
                else:
                    in_frontmatter = False
                    updated_lines.append(line)
                    frontmatter_end_idx = i
                    break
            elif in_frontmatter and line.startswith('status:'):
                updated_lines.append(f'status: {new_status}')
            else:
                updated_lines.append(line)

        # Combine the updated frontmatter with the rest of the content
        if frontmatter_end_idx >= 0:
            new_content = '\n'.join(updated_lines) + '\n' + '\n'.join(lines[frontmatter_end_idx + 1:])
        else:
            # If no frontmatter found, add it at the beginning
            new_content = f"""---
status: {new_status}
---
""" + content

        plan_path.write_text(new_content, encoding='utf-8')
        print(f"Updated plan status to: {new_status}")

        return True

    def get_status(self):
        """Get current status of the skill."""
        plans_count = len(list(self.plans_dir.glob("*.md")))
        needs_action_count = len(list(self.needs_action_dir.glob("*.md")))

        return {
            'plans_created': plans_count,
            'needs_action_items': needs_action_count,
            'handbook_loaded': bool(self.handbook_rules),
            'last_update': datetime.now().isoformat()
        }


def main():
    """Main function to demonstrate the skill."""
    import sys

    if len(sys.argv) != 2:
        print("Usage: python plan_generator_skill.py <vault_path>")
        print("Example: python plan_generator_skill.py ./AI_Employee_Vault")
        return

    vault_path = sys.argv[1]
    skill = PlanGeneratorSkill(vault_path)

    # Generate a sample plan
    print("Generating a sample plan...")
    sample_plan = skill.generate_plan_from_task(
        "Prepare monthly business report for stakeholders",
        task_priority="high",
        task_deadline="2026-03-01"
    )

    # Process any existing Needs_Action items for planning
    print("Processing Needs_Action items for planning...")
    planned_tasks = skill.process_needs_action_for_planning()
    print(f"Created plans for {len(planned_tasks)} tasks.")

    status = skill.get_status()
    print(f"Status: {status}")


if __name__ == "__main__":
    main()